# -*- coding: utf-8 -*-
"""
软件快捷键预设库。

每个预设包含：
  id           唯一标识（英文）
  name         显示名称
  category     分类
  description  一句话说明
  apps        前台程序 exe 名称（支持 * 通配，用于自动模式匹配）
  title_keywords 窗口标题关键词（作为 exe 匹配的补充）
  shortcuts    {键盘组合: {'display': 提示文本}}

注意：所有按键组合必须是 keyboard 库可识别的键名（单字母、数字、
f1-f12、ctrl/shift/alt/win、space/enter/tab 等）。
"""

PRESET_LIBRARY = {
    'windows': {
        'name': 'Windows 系统',
        'category': '系统',
        'description': 'Windows 常用系统快捷键（默认启用，通用常驻）',
        'apps': [],
        'title_keywords': [],
        'shortcuts': {
            'win+d': {'display': 'Win+D 显示桌面'},
            'win+e': {'display': 'Win+E 打开资源管理器'},
            'win+i': {'display': 'Win+I 打开设置'},
            'win+l': {'display': 'Win+L 锁定电脑'},
            'win+s': {'display': 'Win+S 搜索'},
            'win+x': {'display': 'Win+X 打开快捷菜单'},
            'win+shift+s': {'display': 'Win+Shift+S 区域截图'},
            'win+v': {'display': 'Win+V 剪贴板历史'},
            'win+tab': {'display': 'Win+Tab 任务视图'},
            'win+ctrl+d': {'display': 'Win+Ctrl+D 新建虚拟桌面'},
            'win+ctrl+left': {'display': 'Win+Ctrl+← 切换左虚拟桌面'},
            'win+ctrl+right': {'display': 'Win+Ctrl+→ 切换右虚拟桌面'},
            'win+up': {'display': 'Win+↑ 窗口最大化'},
            'win+down': {'display': 'Win+↓ 窗口还原/最小化'},
            'win+left': {'display': 'Win+← 窗口左分屏'},
            'win+right': {'display': 'Win+→ 窗口右分屏'},
            'win+m': {'display': 'Win+M 全部最小化'},
            'win+shift+m': {'display': 'Win+Shift+M 还原最小化窗口'},
            'win+space': {'display': 'Win+Space 切换输入法'},
            'win+g': {'display': 'Win+G 打开游戏栏'},
            'win+p': {'display': 'Win+P 切换投影模式'},
            'win+k': {'display': 'Win+K 投屏/连接设备'},
            'win+print screen': {'display': 'Win+PrtSc 截图保存'},
            'alt+tab': {'display': 'Alt+Tab 切换窗口'},
            'alt+f4': {'display': 'Alt+F4 关闭当前窗口'},
            'ctrl+shift+esc': {'display': 'Ctrl+Shift+Esc 任务管理器'},
            'ctrl+esc': {'display': 'Ctrl+Esc 开始菜单'},
            'ctrl+c': {'display': 'Ctrl+C 复制'},
            'ctrl+v': {'display': 'Ctrl+V 粘贴'},
            'ctrl+x': {'display': 'Ctrl+X 剪切'},
            'ctrl+z': {'display': 'Ctrl+Z 撤销'},
            'ctrl+y': {'display': 'Ctrl+Y 重做'},
            'ctrl+a': {'display': 'Ctrl+A 全选'},
            'ctrl+s': {'display': 'Ctrl+S 保存'},
            'ctrl+f': {'display': 'Ctrl+F 查找'},
            'ctrl+p': {'display': 'Ctrl+P 打印'},
            'ctrl+w': {'display': 'Ctrl+W 关闭标签/窗口'},
            'ctrl+n': {'display': 'Ctrl+N 新建窗口'},
            'ctrl+t': {'display': 'Ctrl+T 新建标签页'},
            'print screen': {'display': 'PrtSc 全屏截图'},
            'caps lock': {'display': 'Caps Lock 大写锁定'},
            'enter': {'display': 'Enter 回车确认'},
            'backspace': {'display': 'Backspace 退格删除'},
            'del': {'display': 'Delete 删除'},
            'page up': {'display': 'Page Up 上翻页'},
            'page down': {'display': 'Page Down 下翻页'},
            'f1': {'display': 'F1 帮助'},
            'f2': {'display': 'F2 重命名'},
            'f3': {'display': 'F3 查找下一个'},
            'f4': {'display': 'F4 地址栏'},
            'f5': {'display': 'F5 刷新'},
            'f6': {'display': 'F6 地址栏定位'},
            'f7': {'display': 'F7 插入模式'},
            'f8': {'display': 'F8 启动菜单'},
            'f9': {'display': 'F9 无默认功能'},
            'f10': {'display': 'F10 菜单栏'},
            'f11': {'display': 'F11 全屏'},
            'f12': {'display': 'F12 另存为'},
        },
    },
    'vscode': {
        'name': 'Visual Studio Code',
        'category': '开发',
        'description': 'VS Code 代码编辑常用快捷键',
        'apps': ['code.exe', 'code - insiders.exe'],
        'title_keywords': [],
        'shortcuts': {
            'ctrl+shift+p': {'display': 'Ctrl+Shift+P 命令面板'},
            'ctrl+p': {'display': 'Ctrl+P 快速打开文件'},
            'ctrl+shift+f': {'display': 'Ctrl+Shift+F 全局搜索'},
            'ctrl+f': {'display': 'Ctrl+F 文件内查找'},
            'f5': {'display': 'F5 开始调试'},
            'shift+f5': {'display': 'Shift+F5 停止调试'},
            'f9': {'display': 'F9 切换断点'},
            'f2': {'display': 'F2 重命名符号'},
            'ctrl+j': {'display': 'Ctrl+J 切换面板(终端)'},
            'ctrl+b': {'display': 'Ctrl+B 切换侧边栏'},
            'ctrl+shift+e': {'display': 'Ctrl+Shift+E 资源管理器'},
            'ctrl+shift+x': {'display': 'Ctrl+Shift+X 扩展商店'},
            'ctrl+shift+g': {'display': 'Ctrl+Shift+G 源代码管理'},
            'ctrl+shift+d': {'display': 'Ctrl+Shift+D 运行与调试'},
            'alt+up': {'display': 'Alt+↑ 上移行'},
            'alt+down': {'display': 'Alt+↓ 下移行'},
            'shift+alt+down': {'display': 'Shift+Alt+↓ 向下复制行'},
            'ctrl+d': {'display': 'Ctrl+D 选中下一个匹配'},
            'ctrl+shift+l': {'display': 'Ctrl+Shift+L 选中全部匹配'},
            'ctrl+/': {'display': 'Ctrl+/ 切换注释'},
            'ctrl+shift+k': {'display': 'Ctrl+Shift+K 删除行'},
            'ctrl+g': {'display': 'Ctrl+G 跳转到行'},
            'ctrl+shift+t': {'display': 'Ctrl+Shift+T 重新打开关闭的编辑器'},
        },
    },
    'excel': {
        'name': 'Microsoft Excel',
        'category': '办公',
        'description': 'Excel 表格处理常用快捷键',
        'apps': ['excel.exe'],
        'title_keywords': ['excel'],
        'shortcuts': {
            'f12': {'display': 'F12 另存为'},
            'f2': {'display': 'F2 编辑单元格'},
            'ctrl+g': {'display': 'Ctrl+G 定位'},
            'ctrl+h': {'display': 'Ctrl+H 替换'},
            'ctrl+home': {'display': 'Ctrl+Home 回到 A1'},
            'ctrl+end': {'display': 'Ctrl+End 数据末尾'},
            'ctrl+up': {'display': 'Ctrl+↑ 跳到数据顶部'},
            'ctrl+down': {'display': 'Ctrl+↓ 跳到数据底部'},
            'ctrl+left': {'display': 'Ctrl+← 跳到数据左端'},
            'ctrl+right': {'display': 'Ctrl+→ 跳到数据右端'},
            'ctrl+1': {'display': 'Ctrl+1 设置单元格格式'},
            'shift+f11': {'display': 'Shift+F11 插入新工作表'},
            'ctrl+d': {'display': 'Ctrl+D 向下填充'},
            'ctrl+r': {'display': 'Ctrl+R 向右填充'},
            'ctrl+t': {'display': 'Ctrl+T 创建表格'},
            'ctrl+k': {'display': 'Ctrl+K 插入超链接'},
            'ctrl+w': {'display': 'Ctrl+W 关闭工作簿'},
        },
    },
    'word': {
        'name': 'Microsoft Word',
        'category': '办公',
        'description': 'Word 文档编辑常用快捷键',
        'apps': ['winword.exe'],
        'title_keywords': ['word'],
        'shortcuts': {
            'f12': {'display': 'F12 另存为'},
            'f4': {'display': 'F4 重复上一步操作'},
            'f7': {'display': 'F7 拼写检查'},
            'ctrl+b': {'display': 'Ctrl+B 加粗'},
            'ctrl+i': {'display': 'Ctrl+I 斜体'},
            'ctrl+u': {'display': 'Ctrl+U 下划线'},
            'ctrl+e': {'display': 'Ctrl+E 居中对齐'},
            'ctrl+l': {'display': 'Ctrl+L 左对齐'},
            'ctrl+r': {'display': 'Ctrl+R 右对齐'},
            'ctrl+j': {'display': 'Ctrl+J 两端对齐'},
            'ctrl+1': {'display': 'Ctrl+1 单倍行距'},
            'ctrl+2': {'display': 'Ctrl+2 双倍行距'},
            'ctrl+5': {'display': 'Ctrl+5 1.5倍行距'},
            'ctrl+shift+c': {'display': 'Ctrl+Shift+C 复制格式'},
            'ctrl+shift+v': {'display': 'Ctrl+Shift+V 粘贴格式'},
            'ctrl+k': {'display': 'Ctrl+K 插入超链接'},
            'ctrl+enter': {'display': 'Ctrl+Enter 分页符'},
            'ctrl+h': {'display': 'Ctrl+H 替换'},
            'ctrl+g': {'display': 'Ctrl+G 定位'},
        },
    },
    'powerpoint': {
        'name': 'Microsoft PowerPoint',
        'category': '办公',
        'description': 'PowerPoint 演示文稿常用快捷键',
        'apps': ['powerpnt.exe'],
        'title_keywords': ['powerpoint'],
        'shortcuts': {
            'ctrl+m': {'display': 'Ctrl+M 新建幻灯片'},
            'ctrl+d': {'display': 'Ctrl+D 复制幻灯片/对象'},
            'ctrl+shift+d': {'display': 'Ctrl+Shift+D 复制所选对象'},
            'f5': {'display': 'F5 从头开始放映'},
            'shift+f5': {'display': 'Shift+F5 从当前页放映'},
            'b': {'display': 'B 黑屏/恢复'},
            'w': {'display': 'W 白屏/恢复'},
            'ctrl+g': {'display': 'Ctrl+G 组合'},
            'ctrl+shift+g': {'display': 'Ctrl+Shift+G 取消组合'},
            'alt+shift+up': {'display': 'Alt+Shift+↑ 上移幻灯片'},
            'alt+shift+down': {'display': 'Alt+Shift+↓ 下移幻灯片'},
            'ctrl+f': {'display': 'Ctrl+F 查找'},
            'f1': {'display': 'F1 帮助'},
        },
    },
    'chrome': {
        'name': 'Google Chrome',
        'category': '浏览器',
        'description': 'Chrome 浏览器常用快捷键',
        'apps': ['chrome.exe'],
        'title_keywords': ['chrome'],
        'shortcuts': {
            'ctrl+t': {'display': 'Ctrl+T 新建标签页'},
            'ctrl+w': {'display': 'Ctrl+W 关闭标签页'},
            'ctrl+shift+t': {'display': 'Ctrl+Shift+T 恢复关闭标签页'},
            'ctrl+tab': {'display': 'Ctrl+Tab 下一个标签页'},
            'ctrl+shift+tab': {'display': 'Ctrl+Shift+Tab 上一个标签页'},
            'ctrl+1': {'display': 'Ctrl+1 跳到第1个标签'},
            'ctrl+9': {'display': 'Ctrl+9 跳到最后一个标签'},
            'ctrl+l': {'display': 'Ctrl+L 聚焦地址栏'},
            'ctrl+f': {'display': 'Ctrl+F 页面查找'},
            'ctrl+d': {'display': 'Ctrl+D 收藏当前页'},
            'ctrl+shift+n': {'display': 'Ctrl+Shift+N 无痕窗口'},
            'ctrl+h': {'display': 'Ctrl+H 历史记录'},
            'ctrl+j': {'display': 'Ctrl+J 下载列表'},
            'ctrl+shift+del': {'display': 'Ctrl+Shift+Del 清除浏览数据'},
            'alt+left': {'display': 'Alt+← 后退'},
            'alt+right': {'display': 'Alt+→ 前进'},
            'f11': {'display': 'F11 全屏'},
            'ctrl+shift+i': {'display': 'Ctrl+Shift+I 开发者工具'},
            'ctrl+r': {'display': 'Ctrl+R 刷新'},
            'ctrl+=': {'display': 'Ctrl+= 页面放大'},
            'ctrl+0': {'display': 'Ctrl+0 页面缩放复位'},
        },
    },
    'autocad': {
        'name': 'AutoCAD',
        'category': '设计/CAD',
        'description': 'AutoCAD 制图常用功能键与命令',
        'apps': ['acad.exe'],
        'title_keywords': ['autocad'],
        'shortcuts': {
            'f1': {'display': 'F1 帮助'},
            'f2': {'display': 'F2 文字窗口'},
            'f3': {'display': 'F3 对象捕捉开关'},
            'f5': {'display': 'F5 等轴测平面'},
            'f6': {'display': 'F6 动态UCS'},
            'f7': {'display': 'F7 网格开关'},
            'f8': {'display': 'F8 正交模式'},
            'f9': {'display': 'F9 捕捉模式'},
            'f10': {'display': 'F10 极轴模式'},
            'f11': {'display': 'F11 对象捕捉追踪'},
            'f12': {'display': 'F12 动态输入'},
            'ctrl+0': {'display': 'Ctrl+0 全屏'},
            'ctrl+1': {'display': 'Ctrl+1 特性面板'},
            'ctrl+2': {'display': 'Ctrl+2 设计中心'},
            'ctrl+3': {'display': 'Ctrl+3 工具选项板'},
            'ctrl+8': {'display': 'Ctrl+8 快速计算器'},
            'ctrl+shift+s': {'display': 'Ctrl+Shift+S 另存为'},
            'ctrl+shift+c': {'display': 'Ctrl+Shift+C 带基点复制'},
            'ctrl+shift+v': {'display': 'Ctrl+Shift+V 粘贴为块'},
            'ctrl+d': {'display': 'Ctrl+D 坐标显示'},
            'ctrl+p': {'display': 'Ctrl+P 打印'},
            'l': {'display': 'L 直线'},
            'c': {'display': 'C 圆'},
            'm': {'display': 'M 移动'},
            'z': {'display': 'Z 缩放'},
            'e': {'display': 'E 删除'},
            'h': {'display': 'H 图案填充'},
            'x': {'display': 'X 分解'},
            'a': {'display': 'A 圆弧'},
            'p': {'display': 'P 平移视图'},
            'i': {'display': 'I 插入块'},
        },
    },
    'nx': {
        'name': 'Siemens NX (UG)',
        'category': '设计/CAD',
        'description': 'NX 三维设计常用文件与视图快捷键',
        'apps': ['nx.exe', 'ugraf.exe'],
        'title_keywords': ['nx', 'ugnx', 'ug nx'],
        'shortcuts': {
            'ctrl+n': {'display': 'Ctrl+N 新建'},
            'ctrl+o': {'display': 'Ctrl+O 打开'},
            'ctrl+s': {'display': 'Ctrl+S 保存'},
            'ctrl+shift+a': {'display': 'Ctrl+Shift+A 另存为'},
            'ctrl+p': {'display': 'Ctrl+P 打印'},
            'f8': {'display': 'F8 定向视图'},
            'ctrl+u': {'display': 'Ctrl+U 执行NX Open'},
        },
    },
    'solidworks': {
        'name': 'SolidWorks',
        'category': '设计/CAD',
        'description': 'SolidWorks 建模常用快捷键',
        'apps': ['sldworks.exe'],
        'title_keywords': ['solidworks'],
        'shortcuts': {
            'space': {'display': 'Space 视图方向对话框'},
            'f': {'display': 'F 缩放至合适'},
            'z': {'display': 'Z 缩小'},
            'shift+z': {'display': 'Shift+Z 放大'},
            'ctrl+tab': {'display': 'Ctrl+Tab 切换文档'},
            'ctrl+q': {'display': 'Ctrl+Q 强制重建'},
            'ctrl+b': {'display': 'Ctrl+B 重建'},
            'ctrl+1': {'display': 'Ctrl+1 标准视图'},
            'ctrl+7': {'display': 'Ctrl+7 等轴测视图'},
            'ctrl+8': {'display': 'Ctrl+8 正视于'},
            'l': {'display': 'L 直线'},
            'c': {'display': 'C 圆'},
            'e': {'display': 'E 拉伸凸台'},
        },
    },
    'sketchup': {
        'name': 'SketchUp',
        'category': '设计/CAD',
        'description': 'SketchUp 草图建模常用快捷键',
        'apps': ['sketchup.exe'],
        'title_keywords': ['sketchup'],
        'shortcuts': {
            'space': {'display': 'Space 选择工具'},
            'm': {'display': 'M 移动'},
            'r': {'display': 'R 矩形'},
            'c': {'display': 'C 圆'},
            'l': {'display': 'L 直线'},
            'p': {'display': 'P 推拉'},
            'e': {'display': 'E 橡皮擦'},
            's': {'display': 'S 缩放'},
            't': {'display': 'T 卷尺测量'},
            'b': {'display': 'B 材质填充'},
            'f': {'display': 'F 偏移'},
            'z': {'display': 'Z 窗口缩放'},
            'shift+z': {'display': 'Shift+Z 缩放至全部'},
            'ctrl+g': {'display': 'Ctrl+G 编组'},
        },
    },
    'blender': {
        'name': 'Blender',
        'category': '三维/建模',
        'description': 'Blender 建模与编辑常用快捷键',
        'apps': ['blender.exe'],
        'title_keywords': ['blender'],
        'shortcuts': {
            'space': {'display': 'Space 工具搜索'},
            'shift+a': {'display': 'Shift+A 添加物体'},
            'g': {'display': 'G 移动'},
            'r': {'display': 'R 旋转'},
            's': {'display': 'S 缩放'},
            'tab': {'display': 'Tab 编辑模式切换'},
            'ctrl+tab': {'display': 'Ctrl+Tab 模式切换'},
            'ctrl+shift+z': {'display': 'Ctrl+Shift+Z 重做'},
            'f9': {'display': 'F9 调整上一步操作'},
            'x': {'display': 'X 删除'},
            'ctrl+r': {'display': 'Ctrl+R 环切'},
            'e': {'display': 'E 挤出'},
            'i': {'display': 'I 插入关键帧'},
            'n': {'display': 'N 侧边栏'},
            't': {'display': 'T 工具栏'},
            'z': {'display': 'Z 着色方式'},
            'alt+z': {'display': 'Alt+Z 透视显示'},
            'a': {'display': 'A 全选'},
            'h': {'display': 'H 隐藏选中'},
            'alt+h': {'display': 'Alt+H 显示全部'},
            'f': {'display': 'F 填充面'},
            'shift+d': {'display': 'Shift+D 复制'},
        },
    },
    '3dsmax': {
        'name': '3ds Max',
        'category': '三维/建模',
        'description': '3ds Max 建模与视图常用快捷键',
        'apps': ['3dsmax.exe'],
        'title_keywords': ['3ds max'],
        'shortcuts': {
            'q': {'display': 'Q 选择工具'},
            'w': {'display': 'W 移动'},
            'e': {'display': 'E 旋转'},
            'r': {'display': 'R 缩放'},
            'm': {'display': 'M 材质编辑器'},
            'f3': {'display': 'F3 线框/实体切换'},
            'f4': {'display': 'F4 边面显示'},
            'h': {'display': 'H 按名称选择'},
            'z': {'display': 'Z 缩放所有视图'},
            'g': {'display': 'G 网格显示切换'},
            '7': {'display': '7 多边形统计'},
            'alt+w': {'display': 'Alt+W 最大化视口'},
            'space': {'display': 'Space 锁定/解锁选择'},
            'f5': {'display': 'F5 X轴约束'},
            'f6': {'display': 'F6 Y轴约束'},
            'f7': {'display': 'F7 Z轴约束'},
            'f8': {'display': 'F8 平面约束'},
        },
    },
    'maya': {
        'name': 'Autodesk Maya',
        'category': '三维/建模',
        'description': 'Maya 动画与建模常用快捷键',
        'apps': ['maya.exe'],
        'title_keywords': ['maya'],
        'shortcuts': {
            'q': {'display': 'Q 选择工具'},
            'w': {'display': 'W 移动'},
            'e': {'display': 'E 旋转'},
            'r': {'display': 'R 缩放'},
            'f': {'display': 'F 框选物体'},
            'a': {'display': 'A 全帧显示'},
            'space': {'display': 'Space 单/多视图切换'},
            '4': {'display': '4 线框显示'},
            '5': {'display': '5 着色显示'},
            '6': {'display': '6 贴图显示'},
            '7': {'display': '7 灯光显示'},
            'ctrl+d': {'display': 'Ctrl+D 复制'},
            'ctrl+shift+d': {'display': 'Ctrl+Shift+D 复制并变换'},
            'ctrl+g': {'display': 'Ctrl+G 编组'},
            'g': {'display': 'G 重复上次操作'},
            'h': {'display': 'H 隐藏选择'},
        },
    },
    'photoshop': {
        'name': 'Adobe Photoshop',
        'category': '图像设计',
        'description': 'Photoshop 图像处理常用快捷键',
        'apps': ['photoshop.exe'],
        'title_keywords': ['photoshop'],
        'shortcuts': {
            'v': {'display': 'V 移动工具'},
            'm': {'display': 'M 选框工具'},
            'l': {'display': 'L 套索工具'},
            'w': {'display': 'W 魔棒工具'},
            'c': {'display': 'C 裁剪工具'},
            'b': {'display': 'B 画笔工具'},
            'e': {'display': 'E 橡皮擦'},
            'g': {'display': 'G 渐变/油漆桶'},
            'h': {'display': 'H 抓手工具'},
            'z': {'display': 'Z 缩放工具'},
            'ctrl+t': {'display': 'Ctrl+T 自由变换'},
            'ctrl+j': {'display': 'Ctrl+J 复制图层'},
            'ctrl+shift+j': {'display': 'Ctrl+Shift+J 剪切到新图层'},
            'ctrl+shift+n': {'display': 'Ctrl+Shift+N 新建图层'},
            'ctrl+shift+s': {'display': 'Ctrl+Shift+S 另存为'},
            'ctrl+alt+shift+s': {'display': 'Ctrl+Alt+Shift+S 导出Web'},
            'ctrl+alt+i': {'display': 'Ctrl+Alt+I 图像大小'},
            'ctrl+alt+c': {'display': 'Ctrl+Alt+C 画布大小'},
            'ctrl+shift+u': {'display': 'Ctrl+Shift+U 去色'},
            'ctrl+l': {'display': 'Ctrl+L 色阶'},
            'ctrl+m': {'display': 'Ctrl+M 曲线'},
            'ctrl+b': {'display': 'Ctrl+B 色彩平衡'},
            'ctrl+u': {'display': 'Ctrl+U 色相/饱和度'},
            'ctrl+e': {'display': 'Ctrl+E 合并图层'},
            'ctrl+shift+e': {'display': 'Ctrl+Shift+E 合并可见图层'},
            'ctrl+alt+shift+e': {'display': 'Ctrl+Alt+Shift+E 盖印图层'},
            'ctrl+g': {'display': 'Ctrl+G 图层编组'},
            'ctrl+shift+g': {'display': 'Ctrl+Shift+G 取消编组'},
            'ctrl+d': {'display': 'Ctrl+D 取消选区'},
            'ctrl+shift+i': {'display': 'Ctrl+Shift+I 反选'},
        },
    },
    'illustrator': {
        'name': 'Adobe Illustrator',
        'category': '图像设计',
        'description': 'Illustrator 矢量设计常用快捷键',
        'apps': ['illustrator.exe'],
        'title_keywords': ['illustrator'],
        'shortcuts': {
            'v': {'display': 'V 选择工具'},
            'a': {'display': 'A 直接选择工具'},
            'p': {'display': 'P 钢笔工具'},
            't': {'display': 'T 文字工具'},
            'm': {'display': 'M 矩形工具'},
            'l': {'display': 'L 椭圆工具'},
            'b': {'display': 'B 画笔工具'},
            's': {'display': 'S 缩放工具'},
            'r': {'display': 'R 旋转工具'},
            'g': {'display': 'G 渐变工具'},
            'ctrl+shift+s': {'display': 'Ctrl+Shift+S 另存为'},
            'ctrl+g': {'display': 'Ctrl+G 编组'},
            'ctrl+shift+g': {'display': 'Ctrl+Shift+G 取消编组'},
            'ctrl+7': {'display': 'Ctrl+7 建立剪切蒙版'},
            'ctrl+y': {'display': 'Ctrl+Y 轮廓预览'},
            'ctrl+0': {'display': 'Ctrl+0 画板适合窗口'},
            'ctrl+1': {'display': 'Ctrl+1 实际大小'},
            'ctrl+d': {'display': 'Ctrl+D 重复变换'},
            'ctrl+f': {'display': 'Ctrl+F 原位粘贴'},
            'ctrl+b': {'display': 'Ctrl+B 粘贴到后面'},
        },
    },
    'premiere': {
        'name': 'Adobe Premiere Pro',
        'category': '视频后期',
        'description': 'Premiere Pro 剪辑常用快捷键',
        'apps': ['adobe premiere pro.exe'],
        'title_keywords': ['premiere'],
        'shortcuts': {
            'space': {'display': 'Space 播放/暂停'},
            'j': {'display': 'J 倒放'},
            'k': {'display': 'K 停止'},
            'l': {'display': 'L 快进'},
            'i': {'display': 'I 设置入点'},
            'o': {'display': 'O 设置出点'},
            'ctrl+k': {'display': 'Ctrl+K 剪切'},
            'ctrl+shift+k': {'display': 'Ctrl+Shift+K 全部轨道剪切'},
            'ctrl+d': {'display': 'Ctrl+D 默认视频过渡'},
            'ctrl+shift+d': {'display': 'Ctrl+Shift+D 默认音频过渡'},
            'ctrl+m': {'display': 'Ctrl+M 导出媒体'},
            'ctrl+i': {'display': 'Ctrl+I 导入素材'},
            'v': {'display': 'V 选择工具'},
            'c': {'display': 'C 剃刀工具'},
            'ctrl+shift+z': {'display': 'Ctrl+Shift+Z 重做'},
        },
    },
    'aftereffects': {
        'name': 'Adobe After Effects',
        'category': '视频后期',
        'description': 'After Effects 合成特效常用快捷键',
        'apps': ['afterfx.exe'],
        'title_keywords': ['after effects'],
        'shortcuts': {
            'space': {'display': 'Space 预览播放'},
            'b': {'display': 'B 工作区起点'},
            'n': {'display': 'N 工作区终点'},
            'ctrl+shift+d': {'display': 'Ctrl+Shift+D 拆分图层'},
            'u': {'display': 'U 显示关键帧'},
            'f9': {'display': 'F9 缓动关键帧'},
            'ctrl+alt+b': {'display': 'Ctrl+Alt+B 工作区贴合合成'},
            'ctrl+m': {'display': 'Ctrl+M 渲染队列'},
            'ctrl+y': {'display': 'Ctrl+Y 新建纯色层'},
            'ctrl+alt+y': {'display': 'Ctrl+Alt+Y 新建调整图层'},
            'ctrl+shift+c': {'display': 'Ctrl+Shift+C 预合成'},
            'p': {'display': 'P 位置'},
            's': {'display': 'S 缩放'},
            'r': {'display': 'R 旋转'},
            't': {'display': 'T 不透明度'},
            'a': {'display': 'A 锚点'},
            'ctrl+k': {'display': 'Ctrl+K 合成设置'},
            'ctrl+i': {'display': 'Ctrl+I 导入素材'},
        },
    },
    'davinci': {
        'name': 'DaVinci Resolve',
        'category': '视频后期',
        'description': '达芬奇剪辑调色常用快捷键',
        'apps': ['resolve.exe'],
        'title_keywords': ['davinci', 'resolve'],
        'shortcuts': {
            'space': {'display': 'Space 播放/暂停'},
            'j': {'display': 'J 倒放'},
            'k': {'display': 'K 停止'},
            'l': {'display': 'L 快进'},
            'i': {'display': 'I 设置入点'},
            'o': {'display': 'O 设置出点'},
            'm': {'display': 'M 添加标记'},
            'ctrl+b': {'display': 'Ctrl+B 在播放头剪切'},
            'shift+backspace': {'display': 'Shift+Backspace 波纹删除'},
            'shift+2': {'display': 'Shift+2 媒体页'},
            'shift+3': {'display': 'Shift+3 快编页'},
            'shift+4': {'display': 'Shift+4 剪辑页'},
            'shift+5': {'display': 'Shift+5 调色页'},
            'shift+6': {'display': 'Shift+6 特效页'},
            'shift+7': {'display': 'Shift+7 交付页'},
            'ctrl+s': {'display': 'Ctrl+S 保存项目'},
            'ctrl+shift+z': {'display': 'Ctrl+Shift+Z 重做'},
        },
    },
    'obs': {
        'name': 'OBS Studio',
        'category': '直播',
        'description': 'OBS 无默认热键，此预设为常见推荐配置，可按需修改',
        'apps': ['obs64.exe', 'obs32.exe'],
        'title_keywords': ['obs studio'],
        'shortcuts': {
            'ctrl+f9': {'display': 'Ctrl+F9 开始录制(推荐)'},
            'ctrl+f10': {'display': 'Ctrl+F10 停止录制(推荐)'},
            'ctrl+f11': {'display': 'Ctrl+F11 保存回放(推荐)'},
            'caps lock': {'display': 'Caps Lock 按键说话(推荐)'},
            'ctrl+shift+p': {'display': 'Ctrl+Shift+P 录制开关(自设)'},
        },
    },
    'guitarpro8': {
        'name': 'Guitar Pro 8',
        'category': '音乐/音频',
        'description': 'Guitar Pro 8 制谱与播放常用快捷键',
        'apps': ['guitarpro8.exe', 'guitar pro 8.exe', 'guitar pro.exe'],
        'title_keywords': ['guitar pro'],
        'shortcuts': {
            'space': {'display': 'Space 播放/停止'},
            'ctrl+shift+insert': {'display': 'Ctrl+Shift+Insert 添加音轨'},
            'ctrl+shift+c': {'display': 'Ctrl+Shift+C 全轨复制'},
            'ctrl+shift+x': {'display': 'Ctrl+Shift+X 全轨剪切'},
            'ctrl+1': {'display': 'Ctrl+1 声部1'},
            'ctrl+2': {'display': 'Ctrl+2 声部2'},
            'ctrl+3': {'display': 'Ctrl+3 声部3'},
            'ctrl+4': {'display': 'Ctrl+4 声部4'},
            'alt+up': {'display': 'Alt+↑ 上移音轨'},
            'alt+down': {'display': 'Alt+↓ 下移音轨'},
            'r': {'display': 'R 输入休止符'},
            'f2': {'display': 'F2 重命名音轨'},
        },
    },
    'studioone': {
        'name': 'Studio One 7',
        'category': '音乐/音频',
        'description': 'PreSonus Studio One 录音编曲常用快捷键',
        'apps': ['studio one*.exe'],
        'title_keywords': ['studio one'],
        'shortcuts': {
            'space': {'display': 'Space 播放/停止'},
            'num multiply': {'display': '小键盘* 录音'},
            'ctrl+r': {'display': 'Ctrl+R 复古录音'},
            'ctrl+e': {'display': 'Ctrl+E 导出混音'},
            'ctrl+p': {'display': 'Ctrl+P 插入乐器'},
            'z': {'display': 'Z 缩放复位'},
            'i': {'display': 'I 自动穿插'},
            'ctrl+b': {'display': 'Ctrl+B 浏览素材库'},
        },
    },
    'flstudio': {
        'name': 'FL Studio',
        'category': '音乐/音频',
        'description': 'FL Studio 编曲常用快捷键',
        'apps': ['fl64.exe', 'fl.exe'],
        'title_keywords': ['fl studio'],
        'shortcuts': {
            'f1': {'display': 'F1 帮助手册'},
            'f5': {'display': 'F5 播放列表窗口'},
            'f9': {'display': 'F9 混音器窗口'},
            'ctrl+p': {'display': 'Ctrl+P 钢琴卷帘'},
            'space': {'display': 'Space 播放/停止'},
            'e': {'display': 'E 钢琴卷帘-选择'},
            'y': {'display': 'Y 钢琴卷帘-静音'},
            'b': {'display': 'B 钢琴卷帘-绘制'},
            'd': {'display': 'D 钢琴卷帘-删除'},
            'z': {'display': 'Z 钢琴卷帘-缩放'},
            'p': {'display': 'P 钢琴卷帘-铅笔'},
            'ctrl+shift+m': {'display': 'Ctrl+Shift+M 导出MIDI'},
        },
    },
    'ableton': {
        'name': 'Ableton Live',
        'category': '音乐/音频',
        'description': 'Ableton Live 音乐制作常用快捷键',
        'apps': ['ableton live*.exe'],
        'title_keywords': ['ableton'],
        'shortcuts': {
            'tab': {'display': 'Tab 会话/编曲视图'},
            'f11': {'display': 'F11 全屏'},
            'ctrl+t': {'display': 'Ctrl+T 新建音频轨'},
            'ctrl+shift+t': {'display': 'Ctrl+Shift+T 新建MIDI轨'},
            'ctrl+d': {'display': 'Ctrl+D 复制'},
            'ctrl+e': {'display': 'Ctrl+E 分割剪辑'},
            'ctrl+u': {'display': 'Ctrl+U 量化'},
            'space': {'display': 'Space 播放/停止'},
            'ctrl+i': {'display': 'Ctrl+I 导入文件'},
            'ctrl+alt+shift+e': {'display': 'Ctrl+Alt+Shift+E 音频引擎开关'},
        },
    },
    'audacity': {
        'name': 'Audacity',
        'category': '音乐/音频',
        'description': 'Audacity 音频编辑常用快捷键',
        'apps': ['audacity.exe'],
        'title_keywords': ['audacity'],
        'shortcuts': {
            'space': {'display': 'Space 播放/停止'},
            'r': {'display': 'R 录音'},
            'p': {'display': 'P 暂停'},
            'ctrl+s': {'display': 'Ctrl+S 保存工程'},
            'ctrl+1': {'display': 'Ctrl+1 放大'},
            'ctrl+2': {'display': 'Ctrl+2 缩小'},
        },
    },
    'notion': {
        'name': 'Notion',
        'category': '效率',
        'description': 'Notion 笔记与知识库常用快捷键',
        'apps': ['notion.exe'],
        'title_keywords': ['notion'],
        'shortcuts': {
            'ctrl+n': {'display': 'Ctrl+N 新建页面'},
            'ctrl+p': {'display': 'Ctrl+P 快速查找'},
            'ctrl+b': {'display': 'Ctrl+B 加粗'},
            'ctrl+i': {'display': 'Ctrl+I 斜体'},
            'ctrl+u': {'display': 'Ctrl+U 下划线'},
            'ctrl+enter': {'display': 'Ctrl+Enter 打开页面'},
            'ctrl+shift+down': {'display': 'Ctrl+Shift+↓ 下移内容块'},
            'ctrl+shift+up': {'display': 'Ctrl+Shift+↑ 上移内容块'},
        },
    },
}

# 预设库显示顺序（windows 系统常驻放最前）
PRESET_ORDER = [
    'windows',
    'vscode',
    'excel',
    'word',
    'powerpoint',
    'chrome',
    'notion',
    'autocad',
    'nx',
    'solidworks',
    'sketchup',
    'blender',
    '3dsmax',
    'maya',
    'photoshop',
    'illustrator',
    'premiere',
    'aftereffects',
    'davinci',
    'obs',
    'guitarpro8',
    'studioone',
    'flstudio',
    'ableton',
    'audacity',
]
